spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: ramzi
    password: ramzi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgresSQLDialect
    database: postgresql
server:
  port: 8060

applicaion:
  config:
    customer-url: http://localhost:8222/api/v1/customers
    product-url: http://localhost:8222/api/v1/products
    payment-url: http://localhost:8222/api/v1/payments