spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ramzi
    password: ramzi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgresSQLDialect
    database: postgresql
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
server:
  port: 8050