apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels:
    app: {{ include "mongodb.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mongodb.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mongodb.name" . }}
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_ROOT_PASSWORD
              value: {{ .Values.mongodbRootPassword }}
            - name: MONGODB_USERNAME
              value: {{ .Values.mongodbUsername }}
            - name: MONGODB_PASSWORD
              value: {{ .Values.mongodbPassword }}
            - name: MONGODB_DATABASE
              value: {{ .Values.mongodbDatabase }}
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: {{ include "mongodb.fullname" . }}-pvc