apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-discovery
  labels:
    app: discovery-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_APPLICATION_NAME
              value: discovery-service
            - name: SPRING_CONFIG_IMPORT
              value: {{ .Values.configServer.url }}
