apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-customer
  labels:
    app: customer-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_APPLICATION_NAME
              value: customer-service
            - name: SPRING_CONFIG_IMPORT
              value: {{ .Values.configServer.url }}
