apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-order-service
  labels:
    app: order-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: order-service
