apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-config-server
  labels:
    app: config-server
spec:
  ports:
    - port: 8888
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: config-server
