apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-payment
  labels:
    app: payment-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            requests:
              memory: '250Mi'
              cpu: '500m'
            limits:
              memory: '512Mi'
              cpu: '500m'
          env:
            - name: SPRING_APPLICATION_NAME
              value: payment-service
            - name: SPRING_CONFIG_IMPORT
              value: {{ .Values.configServer.url }}
